version: "3"

services:

  server:
    image: org.plopl/chess:1.0-SNAPSHOT
    ports:
      - "9090:9090"
      - "8000:8000"

  ui:
    build: ./ui
    volumes:
     - ./ui:/app
    ports:
      - "3000:3000"
#    network_mode: "host"
